---
- name: EOS Config
  eos_config:
    lines:
      - "ip name-server {{ dns_server1 }}"
      - "ip name-server {{ dns_server2 }}"
      - "ip domain-name {{ domain_name }}"
      - "ntp server {{ ntp_server1 }}"
      - "ntp server {{ ntp_server2 }}"

- eos_config:
    backup: yes
